"""Core contract schema and loaders for DiffEHR."""

from .loader import contract_from_dict, load_contract, load_contracts, validate_contract
from .schema import (
    BehavioralRelation,
    BenchmarkResult,
    ClinicalFinding,
    ClinicalTask,
    Contract,
    ContractError,
    ContractProvenance,
    ContractType,
    CounterfactualContract,
    CounterfactualMutation,
    ExpectedBehavior,
    FHIRBundle,
    PatientRecord,
    PerturbationDelta,
    RecordItem,
    RequiredEvidenceCitations,
    TemporalConstraints,
)

__all__ = [
    "BehavioralRelation",
    "BenchmarkResult",
    "ClinicalFinding",
    "ClinicalTask",
    "Contract",
    "ContractError",
    "ContractProvenance",
    "ContractType",
    "CounterfactualContract",
    "CounterfactualMutation",
    "ExpectedBehavior",
    "FHIRBundle",
    "PatientRecord",
    "PerturbationDelta",
    "RecordItem",
    "RequiredEvidenceCitations",
    "TemporalConstraints",
    "contract_from_dict",
    "load_contract",
    "load_contracts",
    "validate_contract",
]
